# Generated by Django 4.2.28 on 2026-02-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedmovie',
            name='original_language',
            field=models.CharField(blank=True, default='en', max_length=10),
        ),
    ]
