# Generated by Django 4.2.28 on 2026-02-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_likedmovie_original_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedmovie',
            name='cast',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='likedmovie',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
