# Generated by Django 6.1.1 on 2026-10-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_likedmovie_cast_likedmovie_runtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedmovie',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='likedmovie',
            name='runtime',
        ),
    ]
