# Generated by Django 4.2.28 on 2026-02-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LikedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('genre_ids', models.JSONField(default=list)),
                ('poster_path', models.CharField(blank=True, max_length=500, null=True)),
                ('overview', models.TextField(blank=True)),
                ('release_date', models.CharField(blank=True, max_length=50)),
                ('vote_average', models.FloatField(default=0)),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-liked_at'],
            },
        ),
    ]
